#!/usr/bin/env node
/**
 * fetch-fonts.mjs — one-time / occasional build-time helper.
 *
 * Downloads the Libre Bodoni + Lato woff2 subsets (latin + latin-ext, which
 * cover the ā/ī diacritics in "Sīlavāpi") from Google Fonts and writes them to
 * src/assets/fonts/, then generates src/assets/css/fonts.css with @font-face
 * rules pointing at the LOCAL files.
 *
 * The point of this script is provenance, not runtime: fonts.gstatic.com is
 * only ever contacted here, by a maintainer, on demand. The production site
 * loads fonts exclusively from its own origin (privacy requirement: zero
 * third-party requests). The downloaded .woff2 files are committed to git.
 *
 * Both families are OFL-licensed, which permits self-hosting and subsetting.
 *
 * Usage:  node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const FONT_DIR = resolve(ROOT, 'src/assets/fonts');
const CSS_OUT = resolve(ROOT, 'src/assets/css/fonts.css');

// A modern-browser UA so the css2 endpoint returns woff2.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0 Safari/537.36';

// Only these named subsets are kept (they carry latin + latin-ext glyphs).
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  {
    family: 'Libre Bodoni',
    css: 'family=Libre+Bodoni:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700',
    slug: 'libre-bodoni',
  },
  {
    family: 'Lato',
    css: 'family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,300;1,400;1,700',
    slug: 'lato',
  },
];

/**
 * Google returns a run of blocks like:
 *   /* latin-ext *\/
 *   @font-face { font-family:'Lato'; font-style:normal; font-weight:400;
 *     src:url(https://…/x.woff2) format('woff2'); unicode-range:… }
 * We parse each block, keep only KEEP_SUBSETS, and rewrite src to a local file.
 */
export function parseBlocks(cssText) {
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/gi;
  let m;
  while ((m = re.exec(cssText)) !== null) {
    const subset = m[1];
    const body = m[2];
    const get = (prop) => {
      const mm = new RegExp(`${prop}\\s*:\\s*([^;]+);`, 'i').exec(body);
      return mm ? mm[1].trim() : '';
    };
    const family = get('font-family').replace(/['"]/g, '');
    const style = get('font-style') || 'normal';
    const weight = get('font-weight') || '400';
    const unicodeRange = get('unicode-range');
    const urlMatch = /url\(([^)]+)\)/i.exec(get('src'));
    const url = urlMatch ? urlMatch[1].replace(/['"]/g, '') : '';
    if (family && url) {
      blocks.push({ subset, family, style, weight, unicodeRange, url });
    }
  }
  return blocks;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const faceRules = [];

  for (const { css, slug } of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?${css}&display=swap`;
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`css2 fetch failed (${res.status}) for ${url}`);
    const cssText = await res.text();
    const blocks = parseBlocks(cssText).filter((b) => KEEP_SUBSETS.has(b.subset));

    for (const b of blocks) {
      const filename = `${slug}-${b.weight}-${b.style}-${b.subset}.woff2`;
      const bin = Buffer.from(
        await (await fetch(b.url, { headers: { 'User-Agent': UA } })).arrayBuffer()
      );
      await writeFile(resolve(FONT_DIR, filename), bin);
      faceRules.push(
        `@font-face{\n` +
          `  font-family:'${b.family}';\n` +
          `  font-style:${b.style};\n` +
          `  font-weight:${b.weight};\n` +
          `  font-display:swap;\n` +
          `  src:url('/assets/fonts/${filename}') format('woff2');\n` +
          `  unicode-range:${b.unicodeRange};\n` +
          `}`
      );
      console.log(`  ↓ ${filename} (${(bin.length / 1024).toFixed(1)} KB)`);
    }
  }

  const header =
    `/* Self-hosted brand fonts — generated by scripts/fetch-fonts.mjs.\n` +
    `   Libre Bodoni + Lato, both OFL. Subsets: latin + latin-ext (covers ā/ī).\n` +
    `   The production site loads fonts ONLY from this origin. Do not edit by hand;\n` +
    `   re-run the script to regenerate. */\n`;
  await writeFile(CSS_OUT, `${header}${faceRules.join('\n')}\n`);
  console.log(`\nWrote ${faceRules.length} @font-face rules → ${CSS_OUT}`);
}

// Only run the network-touching main() when invoked directly (not when a test
// imports parseBlocks).
const invokedDirectly =
  process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (invokedDirectly) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
